create database eventManagement_db;

1.
CREATE TABLE Users (
  UserID INT PRIMARY KEY IDENTITY(1,1),
  fullname VARCHAR(255) NOT NULL,
  Email VARCHAR(255) UNIQUE NOT NULL,
  Password VARCHAR(255) NOT NULL,
  UserType VARCHAR(255) NOT NULL,
  RegistrationDate VARCHAR(255) NOT NULL DEFAULT CURRENT_TIMESTAMP
);


2.
CREATE TABLE Events (
  EventID INT PRIMARY KEY IDENTITY(1,1),
  Title VARCHAR(255) NOT NULL,
  Description TEXT NOT NULL,
  Date DATE NOT NULL,
  Time TIME NOT NULL,
  Location VARCHAR(255) NOT NULL,
  Capacity INT NOT NULL,
  OrganizerID INT,
  FOREIGN KEY (OrganizerID) REFERENCES Users(UserID)
);

5.
CREATE TABLE Tickets (
  TicketID INT PRIMARY KEY IDENTITY(1,1),
  EventID INT NOT NULL,
  UserID INT NOT NULL,
  Type VARCHAR(255) NOT NULL,
  Quantity INT NOT NULL,
  Price DECIMAL(10,2) NOT NULL,
  PurchaseDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (EventID) REFERENCES Events(EventID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

ALTER TABLE Tickets
ADD Status VARCHAR(255) DEFAULT 'Pending';


CREATE TABLE Orders (
  OrderID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL,
  OrderDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TotalPrice DECIMAL(10,2) NOT NULL,
  PaymentID INT,
  FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

ALTER TABLE Orders
ADD FOREIGN KEY (PaymentID) REFERENCES Payments(PaymentID);


CREATE TABLE Payments (
  PaymentID INT PRIMARY KEY IDENTITY(1,1),
  OrderID INT NOT NULL,
  Amount DECIMAL(10,2) NOT NULL,
  Method VARCHAR(255) NOT NULL,
  FOREIGN KEY (OrderID) REFERENCES Orders(OrderID)
);

3.
CREATE TABLE Speakers (
  SpeakerID INT PRIMARY KEY IDENTITY(1,1),
  Name VARCHAR(255) NOT NULL,
  Bio TEXT,
  SocialMediaLinks TEXT
);

4.
CREATE TABLE Sessions (
  SessionID INT PRIMARY KEY IDENTITY(1,1),
  EventID INT NOT NULL,
  Title VARCHAR(255) NOT NULL,
  Description TEXT,
  StartTime TIME NOT NULL,
  EndTime TIME NOT NULL,
  SpeakerID INT,
  FOREIGN KEY (EventID) REFERENCES Events(EventID),
  FOREIGN KEY (SpeakerID) REFERENCES Speakers(SpeakerID)
);

7.
CREATE TABLE Sponsors (
  SponsorID INT PRIMARY KEY IDENTITY(1,1),
  Name VARCHAR(255) NOT NULL,
  LogoURL VARCHAR(255),
  WebsiteURL VARCHAR(255),
  ContactName VARCHAR(255),
  ContactEmail VARCHAR(255) NOT NULL,
  ContactPhone VARCHAR(255),
  EventID INT,
  FOREIGN KEY (EventID) REFERENCES Events(EventID)
);

6.
CREATE TABLE Reviews (
  ReviewID INT PRIMARY KEY IDENTITY(1,1),
  UserID INT NOT NULL,
  EventID INT NOT NULL,
  Comment TEXT,
  SubmissionDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (EventID) REFERENCES Events(EventID)
);
