SELECT TOP (1000) [SponsorID]
      ,[EventID]
	  ,[Name]
      ,[LogoURL]
      ,[WebsiteURL]
      ,[ContactName]
      ,[ContactEmail]
      ,[ContactPhone]
  FROM [eventManagement_db].[dbo].[Sponsors]
